version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    steps:
      - checkout
      - run:
          name: Downloading Node Packages
          command: npm install
      - run:
          name: Downloading Angular
          command: echo y | sudo npm install -g @angular/cli
      - run:
          name: Building Angular Application
          command: ng build --prod
      - run:
          name: Run Sonar Analysis
          command: sudo npm run sonar 